imageSize: 32
bs_secret: 44
num_training: 1
num_secret: 1
num_cover: 1
channel_cover: 1
channel_secret: 1
norm: "batch"
loss: "l2"
beta: 0.75
num_downs: 5
cuda: False
checkpoint: ""
checkpoint_diff: ""
cover_dependent: 1
data: "mnist"
batch_save_frequency: 50
test_diff: "models/steg/ddh_mnist"